theme: jekyll-theme-hacker
title: Cleveland High School Computer Science (CHS CS) Quick Links!
description: Here you can find links to sites for school, events, even computer science!
favicon: favicon.ico
